name: "release"

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/analytics.js"
          generateReleaseNotes: true